version: '2'
services:
    shopapp-app:
        image: shopapp
        external_links:
            - shopapp-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shopapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    shopapp-mysql:
        extends:
            file: mysql.yml
            service: shopapp-mysql
